### ISSUE TITLE
png;base64 logic fails

### ISSUE THREAD

**Issue by Eserim** [suytt/esri.symbol.FillPattern#1]
With this if statement

if( !fill.src.startsWith('data:image/png;base64,') )

My implementation of this (otherwise) excellent code fails.  Removing it makes it all happy.

**Comment by suytt** [comment]
Indeed, the 'startsWith' method is only official as part of ECMAScript 6.
Recent browsers may already support it, but not all.

I will thus replace it with an 'indexOf'.

**Comment by Eserim** [comment]
Would you not still need and "else"?  -I have no idea how it all works, just know I have some very happy users!

Edit - changed to your revised IndexOf - and whilst the code works better (a black filled polygon is drawn instead of nothing) it doesn't take the colour through.

**Comment by suytt** [comment]
a) the IF statement is present only for performance, to avoir to generate the PNG every time the pattern is displayed (zoom, pan,...)

b) the principle is easy, it creates a PNG file "on the fly" with the proper color so there is no need to really store all possible PNG files

c) What browser do you use ? Did you copy the script locally or do you point at the github url ? In IE, when I point at the github url, it does not work because of the "mime type" returned by github is "text/plain" and not "application/javascript"... Let me know if you need an online version.

**Comment by Eserim** [comment]
I use it locally - I have tested in Chrome (latest version of course) and IE10.  Both only work if the if statement is removed and the line executes regardless of condition
